# Tensorflowで学ぶ機械学習・ニューラルネットワーク

In [19]:
import tensorflow as tf
import numpy as np
from math import pi

# GPU確認
# GPUと名がつくデバイスがあればOK
# tf.python.client.device_lib.list_local_devices()

In [7]:
m1 = [[1.0, 2.0],
     [3.0, 4.0]]

m2 = np.array([[1.0, 2.0], [3.0, 4.0]], dtype=np.float32)

m3 = tf.constant([[1.0, 2.0], [3.0, 4.0]])

print(type(m1))
print(type(m2))
print(type(m3))

t1 = tf.convert_to_tensor(m1, dtype=tf.float32)
t2 = tf.convert_to_tensor(m2, dtype=tf.float32)
t3 = tf.convert_to_tensor(m3, dtype=tf.float32)

print(t1)
print(t2)
print(t3)

<class 'list'>
<class 'numpy.ndarray'>
<class 'tensorflow.python.framework.ops.EagerTensor'>
tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)


In [3]:
# 演習2.1
tf.ones([500, 500]) * 0.5

<tf.Tensor: shape=(500, 500), dtype=float32, numpy=
array([[0.5, 0.5, 0.5, ..., 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, ..., 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, ..., 0.5, 0.5, 0.5],
       ...,
       [0.5, 0.5, 0.5, ..., 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, ..., 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, ..., 0.5, 0.5, 0.5]], dtype=float32)>

In [16]:
# リスト2.5 
x = tf.constant([[1, 2]]) # テンソル作成
negMatrix = tf.negative(x) # 符号反転 *この時点では計算されていない
print(negMatrix)

tf.Tensor([[-1 -2]], shape=(1, 2), dtype=int32)


In [29]:
# 演習2.2 ガウス分布
x = 1.0
f_x = tf.multiply(1./tf.sqrt(2.0 * pi),tf.exp(tf.negative(tf.pow(x, 2.0)/2.0)))
print(f_x)

tf.Tensor(0.24197073, shape=(), dtype=float32)
